# TypeProf 0.21.3

# Classes
class IO
  def self.get_cursor_position: -> ([Integer, Integer])
  def self.wait_terminal: (?timeout: Integer|Float) -> bool
  def self.clear_screen: () -> nil
  def read_nonblock: (Integer maxlen) -> String
  def getch: () -> String
  def raw: () { (IO io) -> untyped } -> untyped
  def raw!: () -> self
  def cooked: () { (IO io) -> untyped } -> untyped
  def cooked!: () -> self
  private def _restore_termios: -> self
  def echo?: () -> bool
  def echo=: (bool mode) -> bool
end

# @sidebar error
class IO::EAGAINWaitReadable < StandardError
end
