# @sidebar hardware_device
class HCSR04
  class TimeoutError < StandardError
  end
  class WraparoundError < StandardError
  end

  TIMEOUT_USEC: Integer

  @trig: GPIO
  @echo: GPIO

  def self.new: (trig: Integer, echo: Integer) -> HCSR04
  def distance_cm: () -> Integer
end
