$0: String

module GC
  def self.enable: () -> bool
  def self.disable: () -> bool
  def self.start: () -> bool
end

class ObjectSpace
  def self.count_objects: () -> Hash[Symbol, Integer]
end

class Module
  def define_method: (String | Symbol symbol, ^() [self: instance] -> untyped method) -> Symbol
                   | (String | Symbol symbol) { () [self: instance] -> untyped } -> Symbol
  def const_defined?: (String | Symbol name) -> bool
  def include?: (Module mod) -> bool
  def const_set: (String | Symbol name, untyped value) -> untyped
end

class Class < Module
  def ancestors: () -> Array[Module]
end

class Proc
  def arity: () -> Integer
end

class Array[unchecked out Elem] < Object
  def concat: [U] (Array[U]) -> ::Array[Elem | U]
  def compact: () -> ::Array[Elem]
end

class String
  def sub: (String pattern, String replacement) -> String
  def capitalize: () -> String
end

class Hash[unchecked out Key, unchecked out Value] < Object
  def key?: (Key) -> bool
  def reject: [K, V] { (Key, Value) -> bool } -> ::Hash[Key, Value]
end
