class UsbHid
  KC_NO: Integer
  KC_A: Integer
  KC_B: Integer
  KC_C: Integer
  KC_D: Integer
  KC_E: Integer
  KC_F: Integer
  KC_G: Integer
  KC_H: Integer
  KC_I: Integer
  KC_J: Integer
  KC_K: Integer
  KC_L: Integer
  KC_M: Integer
  KC_N: Integer
  KC_O: Integer
  KC_P: Integer
  KC_Q: Integer
  KC_R: Integer
  KC_S: Integer
  KC_T: Integer
  KC_U: Integer
  KC_V: Integer
  KC_W: Integer
  KC_X: Integer
  KC_Y: Integer
  KC_Z: Integer
  KC_1: Integer
  KC_2: Integer
  KC_3: Integer
  KC_4: Integer
  KC_5: Integer
  KC_6: Integer
  KC_7: Integer
  KC_8: Integer
  KC_9: Integer
  KC_0: Integer
  KC_ENTER: Integer
  KC_ESC: Integer
  KC_BSPACE: Integer
  KC_TAB: Integer
  KC_SPACE: Integer
  KC_MINUS: Integer
  KC_EQUAL: Integer
  KC_LBRACKET: Integer
  KC_RBRACKET: Integer
  KC_BSLASH: Integer
  KC_SCOLON: Integer
  KC_QUOTE: Integer
  KC_GRAVE: Integer
  KC_COMMA: Integer
  KC_DOT: Integer
  KC_SLASH: Integer
  KC_F1: Integer
  KC_F2: Integer
  KC_F3: Integer
  KC_F4: Integer
  KC_F5: Integer
  KC_F6: Integer
  KC_F7: Integer
  KC_F8: Integer
  KC_F9: Integer
  KC_F10: Integer
  KC_F11: Integer
  KC_F12: Integer
  KC_PSCREEN: Integer
  KC_SCROLLLOCK: Integer
  KC_PAUSE: Integer
  KC_INSERT: Integer
  KC_HOME: Integer
  KC_PGUP: Integer
  KC_DELETE: Integer
  KC_END: Integer
  KC_PGDOWN: Integer
  KC_RIGHT: Integer
  KC_LEFT: Integer
  KC_DOWN: Integer
  KC_UP: Integer
  KC_LCTL: Integer
  KC_LSFT: Integer
  KC_LALT: Integer
  KC_LGUI: Integer
  KC_RCTL: Integer
  KC_RSFT: Integer
  KC_RALT: Integer
  KC_RGUI: Integer
  MOUSE_BTN_LEFT: Integer
  MOUSE_BTN_RIGHT: Integer
  MOUSE_BTN_MIDDLE: Integer
  MEDIA_PLAY_PAUSE: Integer
  MEDIA_STOP: Integer
  MEDIA_NEXT: Integer
  MEDIA_PREV: Integer
  MEDIA_VOLUME_UP: Integer
  MEDIA_VOLUME_DOWN: Integer
  MEDIA_MUTE: Integer
end
