source "https://rubygems.org"

gem "rails", "~> 8.1.1"
gem "propshaft"
gem "sqlite3", ">= 2.1"
gem "puma", ">= 5.0"

# Use Active Model has_secure_password
gem "bcrypt", "~> 3.1.7"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Funicular - Local development
gem "funicular", path: "~/work/funicular"

# Tailwind CSS
gem "tailwindcss-rails"

group :development do
  gem "debug", platforms: %i[ mri windows ]
  gem "web-console"
end
