# TypeProf 0.21.3

# Classes
class FAT

  type stat_t = {size: Integer, datetime: String, mode: Integer}

  class Stat
    @stat_hash: stat_t
    def initialize: (stat_t) -> void
    def mode: () -> Integer
  end

  AM_RDO: 1
  AM_HID: 2
  AM_SYS: 4
  AM_DIR: 16
  AM_ARC: 32

  def self._directory?: (String path) -> bool
  def self._exist?: (String path) -> bool
  def self._unlink: (String path) -> 0
  def self._chdir: (String path) -> 0
  def self._mkdir: (String path, String mode) -> 0
  def self._erase: (String path) -> 0
  def self._chmod: (Integer mode, String path) -> 0
  def self._stat: (String path) -> stat_t

  def _getfree: (String path) -> Integer
  def _mkfs: (String path) -> self
  def _setlabel: (String) -> 0
  def _getlabel: (String) -> String
  def _mount: (String path) -> 0
  def _unmount: (String path) -> 0

  @prefix: String
  @fatfs: nil | 0
  @label: String | nil

  def initialize: (?(Symbol|String) drive, ?String? label) -> void
  attr_reader mountpoint: untyped
  def mkfs: -> FAT
  def setlabel: -> 0
  def getlabel: -> String
  def sector_count: -> {total: untyped, free: untyped}
  def mount: (untyped mountpoint) -> untyped
  def unmount: -> nil
  def open_dir: (String path) -> FAT::Dir
  def open_file: (String path, String mode) -> FAT::File
  def chdir: (String path) -> 0
  def erase: -> untyped
  def mkdir: (untyped path, untyped mode) -> untyped
  def chmod: (Integer mode, String path) -> 0
  def stat: (untyped path) -> Stat
  def exist?: (untyped path) -> untyped
  def unlink: (untyped path) -> untyped
  def directory?: (untyped path) -> untyped

  class Dir
    attr_accessor pat: String

    def initialize: (String path) -> void
    def stat_label: -> {attributes: String, datetime: String, size: String}
    def rewind: -> self
    def read: -> String?
    def findnext: -> String?
    def close: -> nil
    def fullpath: -> String
  end

  class File
    def initialize: (String path, String mode) -> void
  end
end
