# TypeProf 0.21.3

# Classes
class FAT
  class VFSMethods
  end

  def self.vfs_methods: -> FAT::VFSMethods
  def self.unixtime_offset=: (Integer) -> Integer

  type stat_t = {size: Integer?, unixtime: Integer?, mode: Integer}
  type driver_t = nil|SPI

  class Stat
    LABEL: String
    @mtime: Time
    @stat_hash: stat_t
    def self.new: (String device, String path) -> instance
    def mode: () -> Integer
    def mode_str: () -> String
    def writable?: () -> bool
    def mtime: () -> Time
    def birthtime: () -> untyped
    def size: () -> Integer
    def directory?: () -> bool
    private def _stat: (String path) -> stat_t
  end

  AM_RDO: 1
  AM_HID: 2
  AM_SYS: 4
  AM_DIR: 16
  AM_ARC: 32

  private def _directory?: (String path) -> bool
  private def _exist?: (String path) -> bool
  private def _unlink: (String path) -> 0
  private def _rename: (String from, String to) -> 0
  private def _chdir: (String path) -> 0
  private def _utime: (Integer unixtime, String path) -> Integer
  private def _mkdir: (String path, Integer mode) -> 0
  private def _erase: (String path) -> 0
  private def _chmod: (Integer mode, String path) -> 0

  def self.init_spi: (String unit, Integer sck_pin, Integer cipo_pin, Integer copi_pin, Integer cs_pin) -> 0
  def getfree: (String path) -> Integer

  private def _mkfs: (String path) -> self
  private def _setlabel: (String) -> 0
  private def _getlabel: (String) -> String
  private def _mount: (String path) -> 0
  private def _unmount: (String path) -> 0

  @fatfs: nil | 0
  @label: String | nil

  def self.new: (Symbol|String device, ?label: String?, ?driver: driver_t) -> FAT

  attr_reader mountpoint: String
  attr_reader prefix: String

  def mkfs: -> FAT
  def setlabel: -> 0
  def getlabel: -> String
  def sector_count: -> {total: Integer, free: Integer}
  def mount: (String mountpoint) -> 0
  def unmount: -> nil
  def open_dir: (String path) -> FAT::Dir
  def open_file: (String path, String mode) -> FAT::File
  def chdir: (String path) -> 0
  def erase: -> 0
  def utime: (Time atime, Time mtime, String path) -> Integer
  def mkdir: (String path, ?Integer mode) -> 0
  def chmod: (Integer mode, String path) -> 0
  def stat: (String path) -> Stat
  def exist?: (String path) -> bool
  def unlink: (String path) -> 0
  def rename: (String from, String to) -> 0
  def directory?: (String path) -> bool

  class Dir
    attr_accessor pat: String

    def initialize: (String path) -> void
    def rewind: -> self
    def read: -> String?
    def findnext: -> String?
    def close: -> nil
    def fullpath: -> String
  end

  class File
    def initialize: (String path, String mode) -> void
    def each_line: () { (String) -> void } -> nil
    def gets: () -> String?
    def puts: (*String) -> nil
    def tell: () -> Integer
    def seek: (Integer offset, ?Integer whence) -> 0
    def eof?: () -> bool
    def read: (?Integer size) -> String?
    def write: (String data) -> Integer
    def close: () -> nil
    def size: () -> Integer
    def expand: (Integer size) -> Integer
    def fsync: () -> 0
  end
end
