class ADNS5050
  def initialize: (sclk: Integer, sdio: Integer, ncs: Integer) -> void
  def _init: (Integer sclk, Integer sdio, Integer ncs) -> 0
  def read: (Integer length) -> String
  def write: (Integer data) -> Integer
end
