# @sidebar error
class IOError < StandardError
end

# @sidebar error
class StandardError < Exception
end

# @sidebar error
class ArgumentError < StandardError
end

# @sidebar error
class NameError < StandardError
end

# @sidebar error
class NoMethodError < StandardError
end

# @sidebar error
class RangeError < StandardError
end

# @sidebar error
class TypeError < StandardError
end

# @sidebar error
class RuntimeError < StandardError
end

# @sidebar error
class ZeroDivisionError < StandardError
end

# @sidebar error
class SyntaxError < StandardError
end
