# @sidebar builtin
class StandardError < Exception
end

# @sidebar builtin
class ArgumentError < StandardError
end

# @sidebar builtin
class NameError < StandardError
end

# @sidebar builtin
class NoMethodError < StandardError
end

# @sidebar builtin
class RangeError < StandardError
end

# @sidebar builtin
class TypeError < StandardError
end

# @sidebar builtin
class RuntimeError < StandardError
end

# @sidebar builtin
class ZeroDivisionError < StandardError
end

# @sidebar builtin
class SyntaxError < StandardError
end
