# TypeProf 0.21.3

# Revealed types
#  lib/picoruby/mrbgems/picoruby-shell/mrblib/command.rb:69 #=> nil

# Classes
class Shell
  class Command
    BUILTIN: Array[String]
    @sandbox: untyped

    def initialize: -> void
    def find_executable: (String name) -> String?
    def exec: (*untyped params) -> void
    def _type: -> nil
    def _echo: -> nil
  end
end
