$shell_sandbox_pool: Shell::SandboxPool?

module Kernel
  def system: (String command) -> bool
  def gets: () -> String?
end

# @private
class Object
  # Workaround.
  # I don't know why `include Kernel` doesn't work.
  def system: (String command) -> bool
  def gets: () -> String?
end
