# TypeProf 0.21.3

# Revealed types
#  /home/hasumi/work/prk_firmware/lib/picoruby/mrbgems/picoruby-shell/mrblib/command.rb:69 #=> nil

# Classes

$LOAD_PATH: Array[String]
ARGV: Array[String]

class Shell
  type rtc_t = PCF8523

  type device_t = GPIO | ADC | I2C | SPI | UART | PWM
  DeviceInstances: Hash[String, device_t]
  def self.get_device: (:gpio, String | Symbol name) -> GPIO
                     | (:adc,  String | Symbol name) -> ADC
                     | (:i2c,  String | Symbol name) -> I2C
                     | (:spi,  String | Symbol name) -> SPI
                     | (:uart, String | Symbol name) -> UART
                     | (:pwm,  String | Symbol name) -> PWM

  LOGO_WIDTH: Integer
  LOGO: Array[String]
  AUTHOR: String
  AUTHOR_COLOR: Integer
  @editor: Editor::Line
  @jobs: Array[Job]

  def self.next_executable: -> {code: String, path: String, crc: Integer}
  def self.setup_rtc: (rtc_t trc) -> void
  def self.setup_sdcard: (SPI spi) -> void

  def self.setup_root_volume: (Symbol drive, ?label: String) -> void
  def self.ensure_system_file: (String path, String code, ?(Integer | nil) crc) -> void
  def self.setup_system_files: (?(String | nil) root, ?force: bool) -> void
  def self.bootstrap: (String file) -> bool
  def self.simple_question: (String question) { (String answer) -> boolish } -> void
  def self.find_executable: (String name) -> String?

  def initialize: (?clean: bool) -> void
  def show_logo: (?Integer color_num)-> void
  def start: (?Symbol mode) -> nil
  def run_shell: -> void
  def run_irb: -> void

  def builtin?: (String name) -> bool
  private def _type: () -> void
  private def _echo: () -> void
  private def _pwd: () -> void
  private def _cd: () -> void
  private def _exit: () -> void
  private def _quit: () -> void
  private def _reboot: () -> void
  private def cleanup_jobs: () -> void
end
