# TypeProf 0.21.3

# Revealed types
#  /home/hasumi/work/prk_firmware/lib/picoruby/mrbgems/picoruby-shell/mrblib/command.rb:69 #=> nil

$shell: Shell
$sandbox: Sandbox

# Classes

ENV: Hash[String, String?]
$LOAD_PATH: Array[String]
ARGV: Array[String]

class Shell
  LOGO_LINES: [String]
  SHORT_LOGO_LINES: [String]
  LOGO_COLOR: String
  AUTHOR_COLOR: String
  @terminal: Terminal::Line

  def self.next_executable: -> {code: String, name: String}

  def setup_root_volume: (Symbol drive, ?label: String) -> void
  def setup_system_files: (?force: bool) -> void

  def initialize: (?clean: bool) -> void
  def simple_question: (String question) { (String answer) -> boolish } -> void
  def show_logo: -> nil
  def start: (?:shell mode) -> nil
  def run_shell: -> void
  def run_irb: -> void
end
