# @io_peripheral
class SPI
  MSB_FIRST: 1
  LSB_FIRST: 0
  DATA_BITS: 8

  type first_bit_t = 0|1#MSB_FIRST|LSB_FIRST
  type mode_t = 0|1|2|3

  DEFAULT_FREQUENCY: 100_000

  @cs: GPIO
  @_unit_info: String

  attr_reader unit: String
  def sck_pin: () -> Integer
  def cipo_pin: () -> Integer
  def copi_pin: () -> Integer
  def cs_pin: () -> Integer

  def initialize: (
    unit: Symbol,
    ?frequency: Integer,
    ?sck_pin: Integer,
    ?cipo_pin: Integer,
    ?copi_pin: Integer,
    ?cs_pin: Integer,
    ?mode: mode_t,
    ?first_bit: first_bit_t
  ) -> void
  def _init: (String unit, Integer frequency, Integer sck_pin, Integer cipo_pin, Integer copo_pin, Integer mode, Integer first_bit, Integer data_bits) -> Integer
  def select: () ?{ (SPI) -> untyped } -> untyped
  def deselect: () -> void
  def write: (*(Integer|String)|Array[Integer] outputs) -> Integer
  def read: (Integer len, ?Integer repeated_tx_data) -> String
  def transfer: (*(Integer|String)|Array[Integer] outputs, ?additional_read_bytes: Integer) -> String
  # private
  def params_to_array: (*(Integer|String)|Array[Integer] params) -> Array[Integer]
  def _write: (Array[Integer]) -> Integer
  def _read: (Integer repeated_tx_data, Integer len) -> (String|Integer)
  def _transfer: (Array[Integer]) -> (String|Integer)
end
