# @sidebar builtin
# @added_by picoruby-metaprog
class Object
  include Kernel

  def send: (Symbol | String name, *untyped args) -> untyped
  def methods: () -> Array[Symbol]
  def instance_variables: () -> Array[Symbol]
  def instance_variable_get: (Symbol name) -> untyped
  def instance_variable_set: (Symbol name, untyped value) -> untyped
  def respond_to?: (Symbol | String name) -> bool
  def __id__: () -> Integer
  alias object_id __id__
  def instance_of?: (Class klass) -> bool
  def const_get: (Symbol name) -> untyped # mruby/c doesn't have Class
  def class?: () -> bool # Alternative to #class==Class
  def self.ancestors: () -> Array[Class]
  def instance_eval: () { (self) -> untyped } -> Object
end

# @added_by picoruby-metaprog
module Kernel
  def caller: (?Integer start, ?Integer length) -> Array[String]
end

# @added_by picoruby-metaprog
module RbConfig
  def self.ruby: () -> (String | nil)
end

# @added_by picoruby-metaprog
class Proc
  def _get_self: () -> Object
  def _set_self: (Object) -> Object
end
