class Object
  def send: (Symbol | String name, *Object args) -> Object
  def methods: () -> Array[Symbol]
  def instance_variables: () -> Array[Symbol]
  def instance_variable_get: (Symbol name) -> Object
  def instance_variable_set: (Symbol name, Object value) -> Object
  def respond_to?: (Symbol | String name) -> bool
  def __id__: () -> Integer
  alias object_id __id__
  def instance_of?: (Class klass) -> bool
end
