# @sidebar hardware_device
class RTD
  type rtd_unit_t = :celsius | :fahrenheit | :kelvin
  DRIVERS: Array[Symbol]

  @r_ref: Float
  @current_gpio: GPIO
  @driver: (:ADC | MCP3424 | MCP3208)
  @driver_type: Symbol
  @channels: Hash[Symbol, (Integer | ADC)]

  attr_accessor sample_count: Integer

  def self.new: (
    driver: (:ADC | MCP3424 | MCP3208),
    current_gpio: GPIO,
    r_ref: (Float | Integer),
    ?channels: Hash[Symbol, (Integer | ADC)]
  ) -> instance
  def read: (?unit: rtd_unit_t) -> Float
  def temperature_in_celsius: (Float) -> Float

  # @sidebar hardware_device
  class PT100 < RTD
  end
end
