class UART
  class MIDI
    include MIDIBASE

    @uart: UART

    def initialize: (
      unit: UART::unit_t,
      ?txd_pin: Integer,
      ?rxd_pin: Integer,
      ?baudrate: Integer,
      ?rx_buffer_size: Integer?,
      ?time_signature: Array[Integer],
      ?max_sysex_bytes: Integer
    ) -> void

    private def midi_read_byte: () -> Integer?
    private def midi_write_byte: (Integer byte) -> (Integer | String)
  end
end
