#!/bin/bash

# AWS ECR login password
# Replace YOUR_REGION with your AWS region (e.g., ap-northeast-1)
export KAMAL_REGISTRY_PASSWORD=$(aws ecr get-login-password --region YOUR_REGION)

# Rails master key
export RAILS_MASTER_KEY=$(cat config/master.key)
