class IO
  type fd_t = Integer | IO

  private def self._popen: (String command, String mode, fd_t in, fd_t out, fd_t err) -> IO
  private def self._pipe: () -> [IO, IO]
end

class Object
  # PicoRuby's open takes (String, String, Integer?) instead of core Kernel#open signature.
  def open: [T] (String file, ?String mode, ?Integer? perm) { (IO) -> T } -> T
          | (String file, ?String mode, ?Integer? perm) -> (IO | nil)
end
