class Machine
  def self.delay_ms: (Integer ms) -> Integer
  def self.sleep: (Integer sec) -> Integer
  def self.deep_sleep: (Integer gpio_pin, bool edge, bool high) -> 0
  def self.using_delay: () { () -> void } -> void
end

$machine_delay: boolish

class Object
  def sleep_ms_orig: (Integer ms) -> Integer
end
