class SSLContext
  VERIFY_NONE: Integer
  VERIFY_PEER: Integer

  def initialize: () -> void
  def ca_file=: (String path) -> String
  def verify_mode=: (Integer mode) -> Integer
  def verify_mode: () -> Integer
end
