class TCPSocket < BasicSocket
  def initialize: (String host, Integer port) -> void
  def self.open: (String host, Integer port) -> TCPSocket
  def self.gethostbyname: (String host) -> Array[String | Integer]
  def addr: () -> Array[String | Integer]
  def connected?: () -> bool
end
