$LOADED_FEATURES: Array[String]

class LoadError < StandardError
end

# @sidebar builtin
# @added_by picoruby-require
class Object
  def require: (String) -> bool
  def load: (String) -> bool
  # private
  def required?: (String) -> bool
  def load_file: (String) -> bool
  def require_file: (String) -> bool
  # picogem_init.c
  def extern: (String path, ?bool force) -> (bool|nil)

  # for CRuby
  def require_relative: (String) -> bool
end

