$LOADED_FEATURES: Array[String]

# @sidebar error
# @added_by picoruby-require
class LoadError < StandardError
end

# @sidebar builtin
# @added_by picoruby-require
module Kernel
  def require: (String name) -> bool
  def load: (String path) -> bool
  private def load_paths: (String name) -> Array[String]
  private def required?: (String name) -> bool
  private def load_file: (String path) -> bool
  private def require_file: (String name) -> bool
  private def extern: (String path, ?bool force) -> (bool|nil)

  # @ignore
  # for CRuby
  def require_relative: (String) -> bool
end
