module Net
  class HTTPGenericRequest
    attr_reader method: String
    attr_reader path: String
    attr_accessor body: String?

    def self.new: (String method, String path, ?Hash[String, String]? initheader) -> HTTPGenericRequest
    def []: (String key) -> String?
    def []=: (String key, String value) -> String
    def delete: (String key) -> String?
    def each_header: () { (String, String) -> void } -> void
    def set_default_headers: (String host, Integer port) -> void
    def to_s: () -> String
    def response_body_permitted?: () -> bool
    def request_body_permitted?: () -> bool
  end

  class HTTPRequest < HTTPGenericRequest
    def self.new: (String path, ?Hash[String, String]? initheader) -> HTTPRequest
  end

  class Get < HTTPRequest
    def self.new: (String path, ?Hash[String, String]? initheader) -> Get
  end

  class Head < HTTPGenericRequest
    def self.new: (String path, ?Hash[String, String]? initheader) -> Head
  end

  class Post < HTTPGenericRequest
    def self.new: (String path, ?Hash[String, String]? initheader) -> Post
  end

  class Put < HTTPGenericRequest
    def self.new: (String path, ?Hash[String, String]? initheader) -> Put
  end

  class Delete < HTTPGenericRequest
    def self.new: (String path, ?Hash[String, String]? initheader) -> Delete
  end

  class Patch < HTTPGenericRequest
    def self.new: (String path, ?Hash[String, String]? initheader) -> Patch
  end

  class Options < HTTPGenericRequest
    def self.new: (String path, ?Hash[String, String]? initheader) -> Options
  end
end
