class MQTTClient
  def initialize: (String host, ?Integer? port, ?String client_id) -> void

  def connect: () -> bool

  def publish: (String topic, String payload) -> bool

  def subscribe: (String topic) -> bool

  def disconnect: () -> bool

  def process_messages: () -> void

  def wait_for_messages: () -> void

  def on_message: () ?{ (String topic, String payload) -> void } -> void

  private

  def _connect_impl: (String host, Integer port, String client_id) -> bool

  def _publish_impl: (String payload, String topic) -> bool

  def _subscribe_impl: (String topic) -> bool

  def _disconnect_impl: () -> bool

  def _pop_packet_impl: () -> (String | nil)

  def _parse_packet_impl: (String packet) -> ([String, String] | nil)

  @host: String
  @port: Integer
  @client_id: String
  @connected: bool
  @message_callback: ^(String, String) -> void
end
