
class EOFError < IOError
end

class IO
  type fd_t = Integer | IO
  def self.new: (*Object args) -> instance
  def self.open: (*Object args) -> instance
               | (*Object args) { () -> instance } -> object
  def self.popen: (String command, ?String mode, ?in: fd_t, ?out: fd_t, ?err: fd_t) -> instance
                | (String command, ?String mode, ?in: fd_t, ?out: fd_t, ?err: fd_t) { () -> instance } -> object
  private def self._popen: (String command, String mode, fd_t in, fd_t out, fd_t err) -> instance
end
