class VRAM
  type page_t = [Integer, Integer, String]
  attr_accessor name: String

  def self.new: (w: Integer, h: Integer, cols: Integer, rows: Integer) -> VRAM
  def pages: (?bool clear_dirty) -> Array[page_t]
  def dirty_pages: (?bool clear_dirty) -> Array[page_t]
  def set_pixel: (Integer x, Integer y, Integer color) -> self
  def draw_rect: (Integer x, Integer y, Integer w, Integer h, Integer color) -> self
  def draw_line: (Integer x0, Integer y0, Integer x1, Integer y1, Integer color) -> self
  def draw_bitmap: (x: Integer, y: Integer, w: Integer, h: Integer, data: Array[Integer]) -> self
  def draw_bytes: (x: Integer, y: Integer, w: Integer, h: Integer, data: String) -> self
  def fill: (Integer color) -> self
  def erase: (Integer x, Integer y, Integer w, Integer h) -> self
end
