class BasicSocket
  def puts: (*untyped args) -> nil
  def gets: (?String sep) -> String?
  def print: (*untyped args) -> nil
  def eof?: () -> bool
  def send: (String data, ?Integer flags) -> Integer
  def recv: (Integer maxlen, ?Integer flags) -> String?
  def peeraddr: () -> Array[String | Integer]
  def remote_address: () -> String
  def local_address: () -> nil

  def write: (String data) -> Integer
  def read: (Integer maxlen) -> String?
  def closed?: () -> bool
  def close: () -> void
  def remote_host: () -> String
  def remote_port: () -> Integer
end
