class SocketError < StandardError
end

class BasicSocket
  CONNECTION_TIMEOUT_MS: Integer
  READ_TIMEOUT_MS: Integer

  @event_queue: Task::Queue?
  @interrupted: bool?
  @int_handler: Proc?
  @previous_int_handler: Signal::handler_t

  def puts: (*untyped args) -> nil
  def gets: (?String sep) -> String?
  def print: (*untyped args) -> nil
  def eof?: () -> bool
  def peeraddr: () -> Array[String | Integer]
  def remote_address: () -> String
  def local_address: () -> nil
  def write: (*String str) -> Integer
  def send: (String data, Integer flags) -> Integer
  def read: (?Integer maxlen) -> (String | nil)
  def readpartial: (Integer maxlen) -> String
  def read_nonblock: (Integer maxlen) -> String?
  def closed?: () -> bool
  def ready?: () -> bool
  def close: () -> void
  def remote_host: () -> String
  def remote_port: () -> Integer
  private def __connection_timeout_ms: () -> Integer
  private def __wait_for_event: (untyped event_queue, String timeout_message) -> void
  private def __readpartial_poll: (Integer maxlen) -> String
  private def __readpartial_event_queue: (Integer maxlen, String timeout_message) -> String
  private def __wait_interruptible: () { () -> untyped } -> untyped
  private def __raise_closed: () -> bot
  private def __install_int_handler: () -> bool
  private def __build_int_handler: () -> Proc
  private def __handle_int_signal: () -> void
  private def __restore_int_handler: () -> void
end
