class SocketError < StandardError
end

class BasicSocket
  O_NONBLOCK: Integer

  def puts: (*untyped args) -> nil
  def gets: (?String sep) -> String?
  def print: (*untyped args) -> nil
  def eof?: () -> bool
  def recv: (Integer maxlen, ?Integer flags) -> String?
  def recv_nonblock: (Integer maxlen, ?Integer flags) -> String?
  def peeraddr: () -> Array[String | Integer]
  def remote_address: () -> String
  def local_address: () -> nil
  def write: (*String str) -> Integer
  def send: (String data, Integer flags) -> Integer
  def read: (Integer maxlen, ?Integer flags) -> String?
  def closed?: () -> bool
  def ready?: () -> bool
  def close: () -> void
  def remote_host: () -> String
  def remote_port: () -> Integer
end
