class SocketDNSResolver
  @event_queue: Task::Queue

  def self.resolve: (String host) -> String
  def initialize: (String host) -> void
  def resolve: (String host) -> String
  private def __status: () -> Integer
  private def __release: () -> nil
  private def __abandon: () -> nil
end
