class SSLSocket < BasicSocket
  attr_reader tcp_socket: TCPSocket
  attr_reader ssl_context: SSLContext

  def self.new: (TCPSocket tcp_socket, SSLContext ssl_context) -> SSLSocket
  def self.open: (String hostname, Integer port, SSLContext ssl_context) -> SSLSocket
  def connect: () -> self
  def addr: () -> Array[String | Integer]
  def connected?: () -> bool
  def peer_cert: () -> nil
  def peer_cert_chain: () -> Array[untyped]
  def cipher: () -> nil
  def ssl_version: () -> String
  def state: () -> String
end
