class UDPSocket < BasicSocket
  def self.new: (?Integer port) -> UDPSocket
  def bind: (String host, Integer port) -> void
  def connect: (String host, Integer port) -> void
  def send: (String data, Integer flags, ?String? host, ?Integer? port) -> Integer
  def recvfrom: (Integer maxlen, ?Integer flags) -> [String, Array[String | Integer]]
  def recvfrom_nonblock: (Integer maxlen, ?Integer flags) -> ([String, Array[String | Integer]] | nil)

  # Incompatible with CRuby but maxlen should be specified in restricted environments
  def read: (Integer maxlen) -> String?
end
