class UDPSocket
  def self.new: (?Integer port) -> UDPSocket
  def bind: (String host, Integer port) -> void
  def connect: (String host, Integer port) -> void
  def send: (String data, Integer flags, ?String? host, ?Integer? port) -> Integer
  def recvfrom: (Integer maxlen, ?Integer flags) -> [String, Array[String | Integer]]
  def recvfrom_nonblock: (Integer maxlen, ?Integer flags) -> ([String, Array[String | Integer]] | nil)
  def read: (?Integer maxlen) -> String?
  def write: (String data) -> Integer
  def eof?: () -> bool
  def close: () -> void
  def closed?: () -> bool
end
