# @sidebar io_peripheral
class ADC
  type pin_t = (Integer|String|Symbol)
  type additional_params_t = Hash[untyped, untyped]

  @additional_params: additional_params_t

  attr_reader input: Integer

  def self.new: (pin_t pin, ?additional_params_t additional_params) -> instance
  def read: () -> Float
  def read_voltage: () -> Float
  def read_raw: () -> Integer

  private def _init: (pin_t pin) -> 0
  private def init_additional_params: () -> self
end
