module Funicular
  module VDOM
    class Differ
      type children_t = Array[child_t]
      def self.diff: (untyped old_node, untyped new_node) -> Array[patch_t]

      private def self.diff_text: (Text old_node, Text new_node) -> Array[patch_t]
      private def self.diff_element: (Element old_node, Element new_node) -> Array[patch_t]
      private def self.diff_props: (Hash[Symbol, untyped] old_props, Hash[Symbol, untyped] new_props) -> Hash[Symbol, untyped]
      private def self.diff_children: (children_t old_children, children_t new_children) -> Array[patch_t]
      private def self.diff_children_with_keys: (children_t old_children, children_t new_children) -> Array[patch_t]
      private def self.diff_children_by_index: (children_t old_children, children_t new_children) -> Array[patch_t]
      private def self.diff_component: (VDOM::Component old_node, VDOM::Component new_node) -> Array[patch_t]

      private def self.props_changed_excluding_procs?: (Hash[Symbol, untyped] old_props, Hash[Symbol, untyped] new_props) -> bool
    end
  end
end
