module Funicular
  class EnvironmentInquirer
    def initialize: (EnvironmentInquirer | String env) -> void
    def to_s: () -> String
    def inspect: () -> String
    def ==: (String other) -> bool
    def development?: () -> bool
  end
end

