module Funicular
  module VDOM
    type patch_t = Array[untyped]
    type child_t = VNode | Array[VNode]

    class VNode
      attr_reader type: Symbol
      def self.new: (Symbol type) -> VNode
    end

    class Element < VNode
      attr_reader tag: String
      attr_reader props: Hash[Symbol, untyped]
      attr_reader children: Array[child_t]

      def self.new: (String tag, ?Hash[Symbol, untyped] props, ?Array[child_t] children) -> Element
      def ==: (untyped other) -> bool
      private def normalize_children: (Array[child_t] children) -> Array[child_t]
    end

    class Text < VNode
      attr_reader content: String

      def self.new: (String content) -> Text
      def ==: (untyped other) -> bool
    end

    class Renderer
      def self.new: (?JS::Object? doc) -> Renderer
      def render: (VDOM::VNode | VDOM::Text | nil vnode, ?JS::Object? parent) -> JS::Object

      private def render_element: (Element element, JS::Object? parent) -> JS::Object
      private def render_text: (VDOM::Text text, JS::Object? parent) -> JS::Object
      private def render_component: (VDOM::Component component_vnode, JS::Object? parent) -> JS::Object
    end

    def self.create_element: (String tag, ?Hash[Symbol, untyped] props, *child_t children) -> Element
    def self.create_text: (String content) -> Text
    def self.render: (VNode vnode, JS::Object container) -> void
    def self.diff: (VNode? old_vnode, VNode? new_vnode) -> Array[patch_t]
    def self.patch: (JS::Object element, Array[patch_t] patches) -> JS::Object

    class Component < VNode
      attr_reader component_class: untyped
      attr_reader props: Hash[Symbol, untyped]
      attr_accessor instance: untyped
      def self.new: (untyped component_class, ?Hash[Symbol, untyped] props) -> Component
      def ==: (untyped other) -> bool
    end
  end
end
