class Object
  PRK_DESCRIPTION: String

  # mrbc
  def relinquish : -> bool
  def sleep_ms : (Integer) -> void
  def suspend_task : () -> void
  def sandbox_state : () -> Integer
  def sandbox_result : () -> untyped
  def sandbox_picorbc: (String) -> bool
  def sandbox_resume: () -> bool

  # PRK
  def required? : (String) -> bool
end
