class USB
  def self.report_raw_hid : (Array[Integer]) -> void
  def self.raw_hid_report_received?: -> bool
  def self.get_last_received_raw_hid_report: -> Array[Integer]
  def self.hid_task : (Integer, String, Integer, Integer, Integer) -> void
  def self.tud_mounted? : () -> bool
  def self.tud_task : -> void
  def self.output_report_changed: () { (Integer) -> void } -> void
  def self.start_observing_output_report: () -> void
  def self.stop_observing_output_report: () -> void
  def self.output_report: () -> Integer
end
