# @sidebar hardware_device
class CYW43
  $_cyw43_country: String

  def self.init: (?String, ?force: bool) -> void
  def self.check_initialized: () -> void
  # @private
  def self._init: (String, bool) -> bool

  # @sidebar hardware_device
  class GPIO
    LED_PIN: Integer
    @pin: Integer
    def initialize: (Integer) -> void
    def write: (Integer) -> 0
    def read: () -> GPIO::gpio_logic_t
  end
end

