class CYW43
  $_cyw43_country: String

  def self.init: (?String, ?force: bool) -> void
  def self.check_initialized: () -> void
  def self._init: (String, bool) -> bool

  class GPIO
    LED_PIN: Integer
    @pin: Integer
    def initialize: (Integer) -> void
    def write: (Integer) -> 0
  end
end

