type httpreturn = {
  status: Integer,
  headers: Hash[String, String],
  body: String
}

class Net
  class HTTPUtil
    def self.format_response: (String?) -> (httpreturn | nil)
  end

  class DNS
    def self.resolve: (String host, bool is_tcp) -> String
  end

  class UDPClient
    def self.send: (String host, Integer port, String content, bool is_dtls) -> String?
    private def self._send_impl: (String host, Integer port, String content, bool is_dtls) -> String?
  end

  class TCPClient
    def self.request: (String host, Integer port, String content, bool is_tls) -> String?
    private def self._request_impl: (String host, Integer port, String content, bool is_tls) -> String?
  end

  class HTTPClient
    @host: String
    def get: (String) -> (httpreturn | nil)
    def get_with_headers: (String, Hash[String, String]) -> (httpreturn | nil)
    def post: (String, Hash[String, String], String) -> (httpreturn | nil)
    def put:  (String, Hash[String, String], String) -> (httpreturn | nil)
  end

  class HTTPSClient
    @host: String
    def get: (String) -> (httpreturn | nil)
    def get_with_headers: (String, Hash[String, String]) -> (httpreturn | nil)
    def post: (String, Hash[String, String], String) -> (httpreturn | nil)
    def put:  (String, Hash[String, String], String) -> (httpreturn | nil)
  end
end
