class GPIO
  ERROR_TIMEOUT:       -1
  ERROR_GENERIC:       -2
  ERROR_NO_DATA:       -3
  ERROR_NOT_PERMITTED: -4
  ERROR_INVALID_ARG:   -5
  ERROR_IO:            -6

  def self.handle_error: (Integer, ?String) -> Integer
end
