# TypeProf 0.21.3

class Vim
  @filepath: String | nil
  @mode: :command | :insert | :normal
  @editor: Editor::Screen
  @command_buffer: Editor::Buffer
  @message: String | nil

  def self.new: (String filepath) -> instance
  def start: -> void
  private def _start: -> void
  def exec_command: (Editor::Buffer buffer) -> (:quit | String | nil)
  def save_file: -> String
end

