# TypeProf 0.21.3

class Vim
  @filepath: String
  @mode: :command | :insert | :normal
  @terminal: Terminal::Editor
  @command_buffer: Terminal::Buffer
  @message: String | nil

  def self.new: (String filepath) -> instance
  def start: -> void
  private def _start: -> void
  def exec_command: (Terminal::Buffer buffer) -> (:quit | String | nil)
  def save_file: -> String
end

