class PicoRubyVM
  class InstructionSequence
    def self.compile: (String code) -> self
    def self.compile_file: (String file) -> self
    def to_binary: () -> String
    def eval: () -> Object
  end
end
