module MIDIBASE
  type event_t = Array[untyped]

  NOTE_OFF: Integer
  NOTE_ON: Integer
  POLYPHONIC_KEY_PRESSURE: Integer
  CONTROL_CHANGE: Integer
  PROGRAM_CHANGE: Integer
  CHANNEL_PRESSURE: Integer
  PITCH_BEND: Integer
  SYSTEM_EXCLUSIVE: Integer
  TIME_CODE_QUARTER_FRAME: Integer
  SONG_POSITION: Integer
  SONG_SELECT: Integer
  TUNE_REQUEST: Integer
  END_OF_EXCLUSIVE: Integer
  TIMING_CLOCK: Integer
  START: Integer
  CONTINUE: Integer
  STOP: Integer
  ACTIVE_SENSING: Integer
  SYSTEM_RESET: Integer
  DEFAULT_MAX_SYSEX_BYTES: Integer
  CHANNEL_EVENTS: Array[Symbol]
  TRANSPORT_EVENTS: Array[Symbol]
  WIRE_EVENTS: Array[Symbol]

  def self.encode: (Symbol command, *(Integer | String) values) -> Array[Integer]
  def self.channel_event: (Integer status, Array[Integer | String] values, Integer count) -> Array[Integer]
  def self.single_value: (Array[Integer | String] values) -> (Integer | String)
  def self.no_value_event: (Array[Integer | String] values, Integer status) -> Array[Integer]
  def self.require_values: (Array[Integer | String] values, Integer count) -> void
  def self.channel_value: (Integer | String value) -> Integer
  def self.data_value: (Integer | String value) -> Integer
  def self.fourteen_bit_value: (Integer | String value) -> Integer

  @midi_parser: Parser?
  @midi_clock: Clock?
  def initialize_midibase: (?time_signature: Array[Integer], ?max_sysex_bytes: Integer) -> self
  def getevent: () -> event_t
  def putevent: (Symbol command, *(Integer | String) values) -> Integer
  def handle: (event_t event, **untyped context) -> Integer
  def bpm: () -> Float?
  def clock_running?: () -> bool
  def time_signature: () -> Array[Integer]?
  def time_signature=: (Array[Integer] signature) -> Array[Integer]
  def position: () -> Array[Integer]
  def bar: () -> Integer
  def beat: () -> Integer
  def tick: () -> Integer
  private def midi_read_byte: () -> Integer?
  private def midi_write_byte: (Integer byte) -> untyped
end
