class Task
  TASKS: Hash[String, Task]

  @proc: Proc
  @args: Array[untyped]
  @sandbox: Sandbox

  attr_reader name: String | nil

  def self.list: () -> Array[Task]

  def initialize: (*untyped) { (*untyped) -> void } -> void
  def name=: (String) -> String
  def suspend: () -> self
  def terminate: () -> self
  def join: (?Integer|nil) -> (self | nil)
  def _start: () -> void
end
