# @sidebar hardware_device
class PCF8523
  ADDRESS: Integer

  attr_reader i2c: I2C

  def self.new : (i2c: I2C) -> instance
  def set_power_management : (?Integer pow) -> Integer
  def current_time= : (Time) -> Time
  def current_time : () -> Time
end
