class PCF8523
  ADDRESS: Integer

  @i2c: I2C

  def initialize : (i2c: I2C) -> void
  def set_power_management : (?Integer pow) -> Integer
  def current_time= : (Time) -> Time
  def current_time : () -> Time
end
