#$DEBUG: bool

module PSG
  type sound_data_t = Array[[Integer, Integer, Integer, Integer]]

  DRUM_CHANNEL: Integer

  @sound_table: Hash[Symbol, Sound]
  @drum_sound_map: Hash[Integer, Symbol]

  def self.note_to_period: (Integer | Float note, ?round: bool) -> Integer
  def self.set_tuning: (?Symbol tuning, ?pitch: Integer | Float) -> Symbol
  def self.set_sound_data: (Symbol name, sound_data_t data) -> Sound
  def self.sound_data: (Symbol name) -> sound_data_t
  def self.sound_duration: (Symbol | Integer | Sound sound) -> Integer
  def self.assign_drum_sound: (Integer note, Symbol? sound_name) -> Symbol?
  private def self.sound_for: (Symbol | Integer | Sound value, bool raise_unknown) -> Sound?

  class Sound
    def initialize: (sound_data_t data) -> void
    def data: () -> sound_data_t
    def duration: () -> Integer
  end

  class Driver
    CHIP_CLOCK: Integer
    SAMPLE_RATE: Integer
    TIMBRES: Hash[Symbol, Integer]

    def self.select_pwm: (Integer left, Integer right) -> void
    def self.select_mcp4922: (Integer ldac) -> void
    def initialize: (Symbol type, **Integer opt) -> void
    def join: () -> void
    def buffer_empty?: () -> bool
    def buffer_flush: () -> nil
    def deinit: () -> nil
    def send_reg: (Integer reg, Integer val, ?Integer tick_delay) -> bool
    def sound: (Integer | Symbol | Sound sound, ?Integer velocity, ?Integer voice) -> bool
    def sound_stop: () -> nil
    def set_lfo: (Integer ch, Integer depth, Integer rate, ?Integer tick_delay) -> bool
    def set_pan: (Integer ch, Integer pan, ?Integer tick_delay) -> bool
    def set_timbre: (Integer ch, Integer timbre_index, ?Integer tick_delay) -> bool
    def set_legato: (Integer ch, Integer legato, ?Integer tick_delay) -> bool
    def mute: (Integer ch, Integer flag, ?Integer tick_delay) -> bool
    def write_reg_direct: (Integer reg, Integer value) -> nil
    def mute_direct: (Integer ch, Integer flag) -> nil

    WAIT_MS: Integer
    def play_prs: (String filename, ?terminate: bool) -> void
    private def invoke: (Symbol command, Integer arg1, Integer arg2, Integer arg3, ?Integer arg4) -> void
  end
end
