#$DEBUG: bool

module PSG
  type voice_program_step_t = [Integer, Integer, Integer, Integer]
  type voice_program_t = Array[voice_program_step_t]

  DRUM_CHANNEL: Integer
  MAX_VOICE_PROGRAM_STEPS: Integer

  @voice_programs: Hash[Symbol, voice_program_t]
  @drum_program_map: Hash[Integer, Symbol]

  def self.note_to_period: (Integer | Float note, ?round: bool) -> Integer
  def self.set_tuning: (?Symbol tuning, ?pitch: Integer | Float) -> Symbol
  def self.define_voice_program: (Symbol name, voice_program_t steps) -> voice_program_t
  def self.voice_program: (Symbol name) -> voice_program_t
  def self.assign_drum_program: (Integer note, Symbol? program_name) -> Symbol?
  def self.drum_program: (Integer note) -> voice_program_t?

  class Driver
    CHIP_CLOCK: Integer
    SAMPLE_RATE: Integer
    TIMBRES: Hash[Symbol, Integer]

    def self.select_pwm: (Integer left, Integer right) -> void
    def self.select_mcp4922: (Integer ldac) -> void
    def initialize: (Symbol type, **Integer opt) -> void
    def join: () -> void
    def buffer_empty?: () -> bool
    def buffer_flush: () -> nil
    def deinit: () -> nil
    def send_reg: (Integer reg, Integer val, ?Integer tick_delay) -> bool
    def voice_write: (Integer voice, Integer tone_period, Integer noise_period, Integer volume, Integer mixer_flags) -> bool
    def set_lfo: (Integer ch, Integer depth, Integer rate, ?Integer tick_delay) -> bool
    def set_pan: (Integer ch, Integer pan, ?Integer tick_delay) -> bool
    def set_timbre: (Integer ch, Integer timbre_index, ?Integer tick_delay) -> bool
    def set_legato: (Integer ch, Integer legato, ?Integer tick_delay) -> bool
    def mute: (Integer ch, Integer flag, ?Integer tick_delay) -> bool
    def write_reg_direct: (Integer reg, Integer value) -> nil
    def mute_direct: (Integer ch, Integer flag) -> nil

    WAIT_MS: Integer
    def play_prs: (String filename, ?terminate: bool) -> void
    private def invoke: (Symbol command, Integer arg1, Integer arg2, Integer arg3, ?Integer arg4) -> void
  end
end
