module PSG
  class MIDIPlayer
    DEFAULT_PITCH_BEND_RANGE: Integer
    MIDI_CHANNELS: Integer

    @driver: PSG::Driver
    @allocator: ::MIDIBASE::VoiceAllocator
    @channels: Array[Integer]?
    @pitch_bend_range: Integer | Float
    @velocities: Array[Integer]
    @volume: Array[Integer]
    @expression: Array[Integer]
    @pan: Array[Integer]
    @bend: Array[Integer]
    @sustain: Array[bool]
    @sustained_notes: Hash[Integer, bool]

    attr_reader allocator: ::MIDIBASE::VoiceAllocator
    def initialize: (PSG::Driver driver, ?voices: Integer, ?channels: Array[Integer]?, ?pitch_bend_range: Integer | Float) -> void
    def handle: (::MIDIBASE::event_t event) -> self
    def all_notes_off: (?Integer? channel, ?immediate: bool) -> self
    private def accept_channel?: (Integer channel) -> bool
    private def note_on: (Integer channel, Integer note, Integer velocity) -> void
    private def note_off: (Integer channel, Integer note) -> void
    private def pitch_bend: (Integer channel, Integer value) -> void
    private def control_change: (Integer channel, Integer controller, Integer value) -> void
    private def sustain_change: (Integer channel, Integer value) -> void
    private def update_channel_volumes: (Integer channel) -> void
    private def update_channel_pan: (Integer channel) -> void
    private def voice_volume: (Integer voice, Integer channel) -> Integer
    private def midi_pan: (Integer channel) -> Integer
    private def write_period: (Integer voice, Integer note, Integer channel) -> void
    private def note_key: (Integer channel, Integer note) -> Integer
    private def write_driver: (Symbol command, *Integer args) -> true
  end
end
