module MbedTLS
  class HMAC
    attr_accessor _digest: String

    type digest_t = "SHA256" | "sha256"

    def initialze: (String key, digest_t digest) -> void
    def update: (String input) -> MbedTLS::HMAC
    def reset: () -> MbedTLS::HMAC
    def digest: () -> String
    def hexdigest: () -> String

  end
end

