$_mbedtls_pers: String

module MbedTLS
  module PKey
    class PKeyError < StandardError
    end

    class PKeyBase
      def sign: (MbedTLS::Digest digest, String input) -> String
      def verify: (MbedTLS::Digest digest, String input, String signature) -> bool
    end

    class RSA < MbedTLS::PKey::PKeyBase
      def self.new: (String key) -> MbedTLS::PKey::RSA
                  | (Integer bits, ?Integer exponent) -> MbedTLS::PKey::RSA
      def self.generate: (Integer bits, ?Integer exponent) -> MbedTLS::PKey::RSA
      def to_pem: () -> String
      alias to_s to_pem
      alias export to_pem
      def public_key: () -> MbedTLS::PKey::PKeyBase
      def public?: () -> bool
      def private?: () -> bool
    end
  end
end

