module MbedTLS
  class Digest
    type algorithm_t = :none | :sha256
    SUPPORTED_ALGORITHMS: Hash[algorithm_t, Integer]

    def initialize: (algorithm_t algorithm) -> void
    def update: (String input) -> MbedTLS::Digest
    def finish: () -> String
  end
end
