# @sidebar prk_firmware
class ConsumerKey
  KEYCODE: Hash[Symbol, Integer]
  ALIAS: Hash[Symbol, Integer]
  VIACODE: Hash[Integer, Symbol]
  MAP_OFFSET: Integer

  def self.keycode: (Symbol sym) -> Integer?
  def self.keycode_from_mapcode: (Integer mapcode) -> Integer
  def self.viacode_from_mapcode: (Integer mapcode) -> Integer?
end
