class UC8151
  PSR:  Integer
  PWR:  Integer
  POF:  Integer
  POFS: Integer
  PON:  Integer
  BTST: Integer
  DSLP: Integer
  DTM1: Integer
  DSP:  Integer
  DRF:  Integer
  DTM2: Integer
  PLL:  Integer
  CDI:  Integer
  TCON: Integer
  TRES: Integer

  @spi: SPI
  @width: Integer
  @height: Integer
  @frame_size: Integer
  @vram: VRAM

  def initialize: (spi: SPI, cs_pin: Integer, dc_pin: Integer,
                   rst_pin: Integer, busy_pin: Integer,
                   ?w: Integer, ?h: Integer) -> void

  def update: () -> void
  def fill: (?Integer color) -> void
  include VRAM::Delegatable
  include Terminus::Drawable
  include Shinonome::Drawable
  def draw_text: (String fontname, Integer x, Integer y, String text, ?Integer scale) -> void
  private def reset: () -> void
  private def busy_wait: () -> void
  private def command: (Integer cmd) -> void
  private def send_data: (*Integer bytes) -> void
  private def send_data_chunked: (String data) -> void
  private def init_display: () -> void
  private def deep_clean: () -> void
end
