class Sounder
  SONGS: Hash[Symbol, String]

  @playing_until: Integer
  @total_duration: Integer
  @last_compiled_song: nil | Symbol
  @locked: bool

  def sounder_init: (Integer) -> void
  def sounder_replay: () -> void

  def lock: () -> void
  def unlock: () -> void
  def replay: () -> void
  def play: (*String | Symbol) -> void
  def compile: (*String | Symbol) -> void
  def add_song: (Symbol name, *String measures) -> void
  def initialize: (Integer) -> void
  def add_note: (Float frequency, Integer duration) -> bool
  def clear_song: () -> void
  def replay_if_key_pressed: () -> void
end
