require "base64"

class EcTest < Picotest::Test
  def test_ec_generate_secp256r1
    ec = MbedTLS::PKey::EC.generate("secp256r1")
    assert_equal(true, ec.to_pem.start_with?("-----BEGIN EC PRIVATE KEY-----\n"))

    ec.free
  end

  def test_ec_generate_default_curve
    ec = MbedTLS::PKey::EC.generate
    assert_equal(true, ec.to_pem.start_with?("-----BEGIN EC PRIVATE KEY-----\n"))

    ec.free
  end

  def test_ec_generate_secp384r1
    ec = MbedTLS::PKey::EC.generate("secp384r1")
    assert_equal(true, ec.to_pem.start_with?("-----BEGIN EC PRIVATE KEY-----\n"))

    ec.free
  end

  def test_ec_public_key
    ec = MbedTLS::PKey::EC.generate("secp256r1")
    public_key = ec.public_key
    assert_equal(true, public_key.to_pem.start_with?("-----BEGIN PUBLIC KEY-----\n"))

    public_key.free
    ec.free
  end

  def test_ec_public?
    ec = MbedTLS::PKey::EC.generate("secp256r1")
    assert_equal(true, ec.public?)

    ec.free
  end

  def test_ec_private?
    ec = MbedTLS::PKey::EC.generate("secp256r1")
    assert_equal(true, ec.private?)

    public_key = ec.public_key
    assert_equal(false, public_key.private?)

    public_key.free
    ec.free
  end

  def test_ec_to_pem_aliases
    ec = MbedTLS::PKey::EC.generate("secp256r1")
    pem = ec.to_pem
    assert_equal(pem, ec.to_s)
    assert_equal(pem, ec.export)

    ec.free
  end

  def test_ec_sign_and_verify
    ec = MbedTLS::PKey::EC.generate("secp256r1")
    data = "Hello World!"
    digest = MbedTLS::Digest.new(:sha256)

    signature = ec.sign(digest, data)
    assert_equal(true, ec.verify(digest, signature, data))
  end

  def test_ec_sign_and_verify_with_public_key
    ec = MbedTLS::PKey::EC.generate("secp256r1")
    data = "Hello World!"
    digest = MbedTLS::Digest.new(:sha256)

    signature = ec.sign(digest, data)
    public_key = ec.public_key
    assert_equal(true, public_key.verify(digest, signature, data))
  end

  def test_ec_verify_wrong_data
    ec = MbedTLS::PKey::EC.generate("secp256r1")
    data = "Hello World!"
    digest = MbedTLS::Digest.new(:sha256)

    signature = ec.sign(digest, data)
    assert_equal(false, ec.verify(digest, signature, "Wrong data"))
  end

  def test_ec_pem_roundtrip
    ec = MbedTLS::PKey::EC.generate("secp256r1")
    pem = ec.to_pem

    ec2 = MbedTLS::PKey::EC.new(pem)
    assert_equal(true, ec2.private?)

    data = "roundtrip test"
    digest = MbedTLS::Digest.new(:sha256)
    signature = ec2.sign(digest, data)
    assert_equal(true, ec2.verify(digest, signature, data))
  end

  def test_ec_new_from_public_pem
    public_key_pem = "-----BEGIN PUBLIC KEY-----\n\
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEp/qBqjAGs1iM6JLMLF/ADyfXr7vp\n\
FHDrv+rNF1KkSkk2IFvT9FkiWcFpoefpDbvKf1MF7e+3bFGgFEu0A8E3pg==\n\
-----END PUBLIC KEY-----\n"
    ec = MbedTLS::PKey::EC.new(public_key_pem)
    assert_equal(true, ec.public?)
    assert_equal(false, ec.private?)

    ec.free
  end

  def test_ec_new_from_private_pem
    private_key_pem = "-----BEGIN EC PRIVATE KEY-----\n\
MHcCAQEEIMwfyqmvT/I5FayRS77yvvJqBRapRWvNwLwSnMFJsmy3oAoGCCqGSM49\n\
AwEHoUQDQgAEp/qBqjAGs1iM6JLMLF/ADyfXr7vpFHDrv+rNF1KkSkk2IFvT9Fki\n\
WcFpoefpDbvKf1MF7e+3bFGgFEu0A8E3pg==\n\
-----END EC PRIVATE KEY-----\n"
    ec = MbedTLS::PKey::EC.new(private_key_pem)
    assert_equal(true, ec.private?)

    data = "test signing"
    digest = MbedTLS::Digest.new(:sha256)
    signature = ec.sign(digest, data)
    assert_equal(true, ec.verify(digest, signature, data))
  end

  # CRuby/OpenSSL interop: verify signature generated by CRuby
  def test_ec_verify_cruby_signature_secp256r1
    public_key_pem = "-----BEGIN PUBLIC KEY-----\n\
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEp/qBqjAGs1iM6JLMLF/ADyfXr7vp\n\
FHDrv+rNF1KkSkk2IFvT9FkiWcFpoefpDbvKf1MF7e+3bFGgFEu0A8E3pg==\n\
-----END PUBLIC KEY-----\n"
    signature_base64 = "MEUCIQDp63Z7aSzKooMh5ggIHA4P1WLkLiChY+sa4qZoq/HxvAIgYxm7RYlPFnrJFNVJufNJCYM44Q1o2mxkWWvif0516rk="

    ec = MbedTLS::PKey::EC.new(public_key_pem)
    data = "Hello World!"
    signature = Base64.decode64(signature_base64)
    digest = MbedTLS::Digest.new(:sha256)

    assert_equal(true, ec.verify(digest, signature, data))
  end
end
