module DRb
  IS_WASM: bool

  module WebSocket

    # WebSocket adapter for DRb
    class Adapter
      def self.new: (untyped ws) -> DRb::WebSocket::Adapter
      def write: (String data) -> void
      def read: (Integer n) -> String
      def close: -> void
      def closed?: -> bool
    end

    # WebSocket server for DRb (microcontroller only)
    class Server
      attr_reader uri: String
      attr_reader front: untyped

      def self.new: (String uri, untyped front, Hash[untyped, untyped] config) -> DRb::WebSocket::Server
      def start: -> self
      def stop: -> void
      def alive?: -> bool
      def run: -> void
      def accept: -> untyped?

      private def handle_client: (Adapter socket) -> void
    end

    # Browser WebSocket adapter (WASM only)
    class BrowserSocket
      def self.new: (String url) -> DRb::WebSocket::BrowserSocket
      def write: (String data) -> void
      def read: (Integer n) -> String
      def close: -> void
      def closed?: -> bool
    end

    def self.connect: (String uri) -> (Adapter | BrowserSocket)
  end

  def self.parse_ws_uri: (String uri) -> ([String, Integer] | String)
  def self._ws_base_create_socket: (String uri) -> untyped
  def self._ws_base_create_server: (String uri, untyped front, Hash[untyped, untyped] config) -> untyped
end
