module JS
  class Object
    type poro_t = JS::Object | String | Symbol | Array[JS::Object] | Integer | Float | nil | bool

    $promise_responses: Hash[Integer, ::Object]
    CALLBACKS: Hash[Integer, Proc]

    def []: (Symbol name) -> JS::Object
    def addEventListener: (String event_type) { (String event_json) -> void } -> Integer # callback_id
    def to_binary: () -> ::Object
    def to_poro: () -> poro_t
    def fetch: (String url) { (::Object response) -> void } -> void
    private def method_missing: (Symbol method_name, ?String arg) -> JS::Object
    private def _add_event_listener: (Integer callback_id, String event_type) -> nil
    private def _fetch_and_suspend: (String url, Integer callback_id) -> nil
    private def _to_binary_and_suspend: (Integer callback_id) -> nil
  end

  def global: () -> JS::Object
end
