class Buddie
  @window: JS::Object
  @document: JS::Object
  @content_div: JS::Object

  def is_numeric?: (String? str) -> bool
  def initialize: () -> void
  def render: () -> untyped
  def render_index: (Integer page) -> untyped
  def render_article: (String article_id) -> untyped
  def parse_front_matter: (String text) -> [Hash[String, String], String]
  def parse_query_string: (String query_part) -> Hash[String, String]
  def highlight_code: () -> void
  def setup_external_links: () -> void
  def render_404: (?String title, ?String message) -> untyped
  def self.run: () -> void
end
