module KarmaticArcade
  def self._10: (String text, ?Integer scale) -> bdffont_result_t

  def self.draw: (String name, String line, ?Integer scale) { (bdffont_result_t) -> void } -> void
               | (String name, String line, ?Integer scale) -> bdffont_result_t

  module Drawable
    def draw_bitmap: (x: Integer, y: Integer, w: Integer, h: Integer, data: Array[Integer]) -> nil
    def draw_karmatic_arcade: (String name, Integer x, Integer y, String text, ?Integer scale) -> nil
    def bdffont_draw_result: (bdffont_result_t result, Integer x, Integer y) -> nil
  end
end
