class IIRFilter
  COEFF_SHIFT: Integer
  MAX_COEFF_SHIFT: Integer
  FILTER_FEEDFORWARD: Integer

  @filterd_value: Integer

  def self.new: () -> instance
  def filter: (Integer raw_value) -> Integer
end
