class IIRFilter
  COEFF_SHIFT: Integer
  MAX_COEFF_SHIFT: Integer

  @filterd_value: Integer
  @feedforward: Integer

  def initialize: (Integer bit_depth) -> void
  def filter: (Integer raw_value) -> Integer
end
