# @hardware_device
class EC21
  type log_t = Hash[Symbol, String]

  DEFAULT_LOG_SIZE: Integer

  @uart: UART
  @log_size: Integer
  @log: Array[log_t]

  def initialize: (unit: (Symbol|String), txd_pin: Integer, rxd_pin: Integer, baudrate: Integer, log_size: Integer) -> void
  def addlog: (String cmd, String res) -> nil
  def call_and_response: (String cmd, String expected_response, ?String? error_response, ?Integer timeout) -> bool
  def check_sim_status: () -> bool

  # @hardware_device
  class SoracomBeamUDP < EC21
    def configure_and_activate_context: () -> bool
    def connect_and_send: (String data) -> bool
  end
end
