# TypeProf 0.14.1

# Global variables

class RotaryEncoder
  @proc_cw:  (^() -> void | Proc)
  @proc_ccw: (^() -> void | Proc)
  @pin_a: Integer
  @pin_b: Integer
  @partner_keycode_cw: Integer
  @partner_keycode_ccw: Integer
  @split_left: bool
  @partner_encoders: Array[RotaryEncoder]
  @number: Integer

  def init_encoder: (Integer, Integer) -> Integer
  def consume_encoder: (Integer) -> Integer

  def initialize: (Integer pin_a, Integer pin_b) -> void
  def init_pins: () -> void
  def create_keycodes: (Integer) -> void
  def call_proc_if: (Integer) -> void
  def configure: (Symbol symbol) -> void
  def left?: () -> bool
  def right?: () -> bool
  def clockwise: () { () -> void } -> void
  def counterclockwise: () { () -> void } -> void
  def consume_rotation_anchor: () -> void
  def consume_rotation_partner: () -> Integer
end
