class Sandbox
  TIMEOUT: Integer

  @result: Object | nil
  @script: String
  @state: Integer
  @binding: Binding

  attr_accessor error: Exception?

  def compile: (String) -> bool
  def suspend: () -> void
  def state: () -> Integer
  def result: () -> untyped
  def wait: (?Integer timeout) -> bool
  def execute: () -> bool
end

class RubyVM::InstructionSequence
  def self.compile: (String) -> self
end
