module JWT
  def self.encode: (String payload, String|nil secret, String|bool validate, ?algorithm: String) -> String
  def self.decode: (String token, String|nil secret, String|bool validate) -> String
end
