class MCP3204
  DEFAULT_FREQUENCY: 500_000

  @spi: SPI
  @cs: GPIO

  def initialize: (
    unit: Symbol,
    ?frequency: Integer,
    ?sck_pin: Integer,
    ?cipo_pin: Integer,
    ?copi_pin: Integer,
    ?cs_pin: Integer
  ) -> void
  def read: (Integer channel) -> String
end
