name: C/C++ CI

on:
  push:
    branches:
      - master
      - ci-test
  pull_request:
    branches:
      - master

env:
  GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

permissions:
  contents: write
  pull-requests: write

jobs:

  test-steep:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout recursive
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '4.0.1'
        bundler-cache: true

    - name: Test Steep
      run: rake test:gems:steep

  test-picoruby:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout recursive
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '4.0.1'
        bundler-cache: true

    - name: Test PicoRuby
      run: rake test:gems:picoruby

  test-femtoruby:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout recursive
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '4.0.1'
        bundler-cache: true

    - name: Test FemtoRuby
      run: rake test:gems:femtoruby

  test-wasm:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout recursive
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '4.0.1'
        bundler-cache: true

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: '3.1.64'

    - name: Test WASM
      run: rake test:gems:wasm